version: '{branch}-{build}'

init:
  # Gather some basic build environment details.
  - rem set
  - dir "%ProgramFiles(x86)%\Microsoft Visual Studio *" /b /o
  - dir "%ProgramFiles%\Microsoft SDKs\Windows" /b /o
  - dir "%SystemDrive%\Qt\5.*" /b /o

install:
  - dir "C:\Qt\5.5\mingw492_32\bin"
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  
build_script:
  - qmake.exe tetris.pro
  - mingw32-make 
  - qmake.exe tetris_tests.pro
  - mingw32-make
  - ./tetris_tests
