os: unstable


install:
  - set QTDIR=C:\Qt\5.5\mingw492_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  
build_script:
  - qmake tetris.pro
  - mingw32-make 
  - qmake tetris_tests.pro
  - mingw32-make
  - ./tetris_tests
