#Linux build

env:
  - QTVER=55 
  
language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-add-repository ppa:beineri/opt-qt55 -y
  - sudo apt-get update -q

install:
    - sudo apt-get install qt55quick1 qt55creator

    

script:
    - qmake tetris.pro
    - make
    - qmake tetris_tests.pro
    - make
    - ./tetris_tests
