#Linux build

env:
  - QTVER=55 

before_install:
    - sudo apt-add-repository ppa:beineri/opt-qt55 -y
    - sudo apt-get update -q

install:
    - sudo apt-get install qt-latest qtcreator-latest

    

script:
    - qmake tetris
    - make
    - qmake tetris_tests
    - make
    - ./tetris_tests
