#Linux build

env:
  - QTVER=55 
  
language: cpp

compiler:
  - gcc

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update -q

install:
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
    - sudo apt-get install qtdeclarative5-dev qtcreator qt5-qmake

    

script:
    - qmake tetris.pro
    - make
    - qmake tetris_tests.pro
    - make
    - ./tetris_tests
