#Linux build

env:
  - QTVER=55 
  
language: cpp

compiler:
  - g++

before_install:
  - sudo apt-add-repository ppa:beineri/opt-qt55 -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install -qq g++-5
  - export CXX="g++-5"
  
install:
    - sudo apt-get install qt55base qt55quick1 qt55creator qt55tools
    - source /opt/qt55/bin/qt55-env.sh

    
script:
    - g++ -v
    - qmake tetris.pro
    - make
    - qmake tetris_tests.pro
    - make
    - ./tetris_tests
